# Generated by Django 5.2.3 on 2025-07-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('car_count', models.IntegerField()),
                ('car_value', models.FloatField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
    ]
