# Generated by Django 5.2.3 on 2025-07-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_carinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
